spring.datasource.url=jdbc:h2:mem:feedbackdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=p123
spring.h2.console.enabled=true
aws.accessKeyId=AKIAYGVI3ALTAEFZXPWW
aws.secretAccessKey=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
aws.region=us-east-1
spring.mvc.cors.allowed-origins=*
spring.mvc.cors.allowed-methods=GET,POST,PUT,DELETE